
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Aftas
    username: postgres
    password: Nouhailakhaouti1...
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
   change-log: db/changelog/master.xml